config/routes.rb
Rails.application.routes.draw do

  resources :blocks
  resources :works, path: 'our_work'
  resources :contacts
  post 'newcomment', to: 'contacts#create'
  get 'dashboard', to: 'dashboard#index'
  get 'who_we_are', to: 'home#whoweare'
  get 'lets-talk', to: 'home#letstalk'


  get 'privacypolicy', to: 'home#privacypolicy'


  devise_for :users
  resources :reviews
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, path: 'our_two_cents'
  resources :services, path: 'whatwedo'
  resources :sections, except: [ :show]
  root 'home#index'

  # resources :services, path: 'whatwedo', :except => [:edit, :new, :destroy] do
  # 	resources :sections, path: ''
  #   # , only: [:index, :show]
  # end


  resources :works do
    resources :blocks
  end


  resources :services, path: 'whatwedo'  do
    resources :sections, path: 'topic'
  end


end

app/models/service.rb
class Service < ApplicationRecord

	has_many :sections
	
	extend FriendlyId
	friendly_id :title, use: :slugged

	
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]


  def index
    @services = Service.all
  end


  def show
    @sections = Section.where(service_id: @service.id)
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_service
      @service = Service.friendly.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:title, :sub_header, :summary, :service_name, :cover)
    end
end

app/helpers/services_helper.rb
module ServicesHelper

	def services
		Service.order("created_at ASC")
	end
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true, class: 'form') do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :sub_header %>
    <%= form.text_field :sub_header, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :service_name %>
    <%= form.text_field :service_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Publish', class: 'btn-large' %>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="_page post">

	<section class="sectionfiller">
		<div class="container boxIt">
			<h1>Editing Service</h1>
			<%= render 'form', service: @service %>
		</div>
	</section>

</div>

app/views/services/index.html.erb
<% set_meta_tags title: 'What we do | Our Services',
                 description: 'Topics we are talking about',
                 keywords: 'Somali web development agency, Webdevelopment agency, london web development agency' %>


<div class="_page">
<p id="notice"><%= notice %></p>

<section class="sectionfiller">
  <div class="container boxIt">
      <h1 class="title">WHAT WE DO</h1>
      <p class="content">
          We do Digital. We’re your web design company, web development agency and digital marketing team all rolled into one very special integrated digital service.
      </p>
  </div>
</section>


<% @services.each do |service| %>
  <section class="sectionfiller">
    <div class="featuredImage" style="background-image: url('<%= service.cover(:original) %>')"></div>

    <div class="container boxIt">
        <h1 class="title"><%= service.title %></h1>
        <p class="content">
            <%= service.summary %>
        </p>
        <a class="itemLink" href="<%= service_path(service) %>">
            Learn More About Our <%= service.service_name %> Services
        <div class="btm"></div>
        </a>
    </div>
  </section>
  <%#= link_to 'Edit', edit_service_path(service) %>
  <%#= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


<% if user_signed_in? %>
  <div class="container">
    <%= link_to 'New Service', new_service_path %>
  </div>
<% end %>



<div class="spaced_footer"></div>

</div>

app/views/services/new.html.erb
<div class="_page post">

	<section class="sectionfiller">
		<div class="container boxIt">
			<h1>New Service</h1>
			<%= render 'form', service: @service %>
		</div>
	</section>

</div>

app/views/services/show.html.erb
<% set_meta_tags title: @service.title,
                 description: @service.sub_header,
                 keywords: 'Somali web development agency, Webdevelopment agency, london web development agency' %>

<div class="_page">


	<section class="sectionfiller">
	    <div class="container boxIt">
	        <h1 class="title"><%= @service.title %></h1>
	        <% if @service.sub_header %>
	        	<h2 class="subheader"><%= @service.sub_header %></h2>
	        <% end %>
	        <p class="content">
	            <%= @service.summary %>
	        </p>

		<% if user_signed_in? %>

	        <%= link_to 'Edit', edit_service_path(@service) %> |
	        <%= link_to 'Back', services_path %>

        <% end %>

	    </div>
	</section>

	<% @sections.each do |section| %>

		<section class="sectionfiller">
		    <div class="featuredImage" style="background-image: url('<%= section.cover(:original) %>')"></div>

		    <div class="container boxIt">
		        <h1 class="title"><%= section.title %></h1>
		        <p class="content">
		            <%= section.summary %>
		        </p>
		        <a class="itemLink" href="<%= service_section_path(@service, section) %>">
		            Learn More About Our <%= section.service_name %> Services
		        <div class="btm"></div>
		        </a>
		         <%#= link_to 'Destroy', section, method: :delete, class: "itemLink" %>
		    </div>
		</section>

	<% end %>


	<p id="notice"><%= notice %></p>
	<div class="spaced_footer"></div>

</div>