config/routes.rb
Rails.application.routes.draw do

  resources :blocks
  resources :works, path: 'our_work'
  resources :contacts
  post 'newcomment', to: 'contacts#create'
  get 'dashboard', to: 'dashboard#index'
  get 'who_we_are', to: 'home#whoweare'
  get 'lets-talk', to: 'home#letstalk'


  get 'privacypolicy', to: 'home#privacypolicy'


  devise_for :users
  resources :reviews
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, path: 'our_two_cents'
  resources :services, path: 'whatwedo'
  resources :sections, except: [ :show]
  root 'home#index'

  # resources :services, path: 'whatwedo', :except => [:edit, :new, :destroy] do
  # 	resources :sections, path: ''
  #   # , only: [:index, :show]
  # end


  resources :works do
    resources :blocks
  end


  resources :services, path: 'whatwedo'  do
    resources :sections, path: 'topic'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :work
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged

	has_attached_file :featuredimage, styles: { medium: "600x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :featuredimage, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/section.rb
class Section < ApplicationRecord

	belongs_to :service

	extend FriendlyId
	friendly_id :title, use: :slugged
	
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :sections
	
	extend FriendlyId
	friendly_id :title, use: :slugged

	
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # , :registerable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord

	extend FriendlyId
	friendly_id :company_name, use: :slugged

	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

	has_many :blocks

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

		@title = 'Web development Agency'
		@description = 'Msugroo Landing page'
		@keywords = 'Somali web development agency, Webdevelopment agency, london web development agency'

		@posts = Post.order("created_at DESC").limit(3)
		@works = Work.order("created_at DESC").limit(4)
	end

	def whoweare
	end

	def letstalk
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def random_review
		Review.order("RANDOM()").first
	end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper

	def services
		Service.order("created_at ASC")
	end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/addons/_adminnav.html.erb
<div class="adminnav">
	<div class="container-fluid">
		<% if user_signed_in? %>
		  <%= link_to 'Dashboard',dashboard_path %>
		  <li>
		  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Login', new_user_session_path)  %>  
		  </li>
		<% end %>

		<% if user_signed_in? %>
		  <li>
		  <%#= link_to('Edit registration', edit_user_registration_path) %>
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Register', new_user_registration_path)  %>
		  </li>
		<% end %>
	</div>

</div>

app/views/addons/_footer.html.erb
<div class="footer">
        <div class="callToAction">
            <div class="row">
                <div class="col msg">
                    If you're a forward-thinking business with an interesting branding or web design concept, drop us a line.
                </div>
                <div class="col-md-3 btnSpace">
                    <a class="callToActionBTN" href="/lets-talk">Let's Talk</a>
                </div>
            </div>
        </div>   

        <div class="container">
            <div class="row">
                <div class="col">

                    <div class="row">
                        <div class="col">
                            <h3 class="resource_title">Key Services</h3>

                            <% services.each do |s| %>
                                <li class="resource_link">
                                    <a href="<%= service_path(s)%>" class="resource_link">
                                        <%= s.title %>
                                    </a>
                                </li>
                            <% end %>
                        </div>
                        <div class="col">
                            <h3 class="resource_title">Who We Are</h3>
                            <li class="resource_link"><a href="<%= works_path %>">Our Work</a></li>
                            <li class="resource_link"><a href="<%= posts_path %>">Our Two Cents</a></li>
                            <li class="resource_link"><a href="/privacypolicy">Privacy Policy</a></li>
                        </div>
                        <div class="col">
                            <h3 class="resource_title">Resources</h3>
                            <li class="resource_link"><a href="#">Terms</a></li>
                            <li class="resource_link"><a href="/sitemap.xml">Sitemap</a></li>
                            <li class="resource_link"><a href="/lets-talk">Lets Talk</a></li>
                        </div>
                    </div>

                </div>
                <% if random_review %>
                <div class="col-md-5">
                    <%= render  'addons/randomreview' %>
                </div>
                <% end %>
            </div>
            
        </div>
        <div class="made_ldn">
            Made With <i class="fas fa-heart color-red"></i> In London
        </div>
    </div>

app/views/addons/_navbar.html.erb
<input type="checkbox" id="mobile" class="hidden">
<div id="nav">
  <div class="brand">
    <a href="<%= root_path %>">
    <div class="symbol"></div>
    <h1 class="sitename">MSUGROO</h1>
    </a>
  </div>
  <div class="right">

    <div class="collapsible">
    
    <a class="NavLink" href="/who_we_are">WHO WE ARE</a> 
    <a class="NavLink" href="<%= services_path %>">WHAT WE DO</a> 
    <a class="NavLink" href="<%= posts_path %>">OUR TWO CENTS</a> 
    <a class="NavLink" href="<%= works_path %>">OUR WORK</a> 
    <a class="NavButton" href="<%= lets_talk_path %>">LET'S TALK</a>

      <label for="mobile" class="btn-menu mobile-only fixed-to-right btn-large">
        <i class="fas fa-times"></i>
      </label>
    </div>
    
    <label for="mobile" class="btn-menu mobile-only">
      <i class="fas fa-bars"></i>
    </label>

  </div>
</div>

app/views/addons/_randomreview.html.erb
<div class="review">

    <div class="userinfo">
        <div class="avatar" style="background-image: url(<%= random_review.avatar(:medium)%>)"></div>
        <label class="username"> <%= random_review.company_name %> </label> <br>
        <label class="company_name"> <%= random_review.industry %></label>
        <button class="close"><i class="fas fa-sync"></i></button>
    </div>
    <div class="content">
        <%= random_review.comment %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'MSugroo', reverse: true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap-grid.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

    <% if current_page?('/dashboard') || current_page?('/dashboard/') %>
      <!-- Custom fonts for this template-->
      <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
      <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

      <!-- Custom styles for this template-->
      <link href="css/sb-admin-2.min.css" rel="stylesheet">
      <% end %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <% if current_page?('/dashboard') || current_page?('/edit') || current_page?('/new') %>
    <body id="page-top">

      <div id="wrapper">
        <%= yield %>
      </div>

      <!-- Bootstrap core JavaScript-->
      <script src="vendor/jquery/jquery.min.js"></script>
      <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

      <!-- Core plugin JavaScript-->
      <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

      <!-- Custom scripts for all pages-->
      <script src="js/sb-admin-2.min.js"></script>

      <!-- Page level plugins -->
      <script src="vendor/chart.js/Chart.min.js"></script>

      <!-- Page level custom scripts -->
      <script src="./js/demo/chart-area-demo.js"></script>
      <script src="./js/demo/chart-pie-demo.js"></script>
    </body>
    <% else %>
    <body class="mainsite">

      <% if user_signed_in? %>
        <%= render 'addons/adminnav' %>
      <% end %>

      <%= render 'addons/navbar' %>
      <%= yield %>
      <%= render 'addons/footer' %>
    </body>

    <% end %>


    <%= javascript_pack_tag 'application' %>

    
</html>