config/routes.rb
Rails.application.routes.draw do

  resources :blocks
  resources :works, path: 'our_work'
  resources :contacts
  post 'newcomment', to: 'contacts#create'
  get 'dashboard', to: 'dashboard#index'
  get 'who_we_are', to: 'home#whoweare'
  get 'lets-talk', to: 'home#letstalk'


  get 'privacypolicy', to: 'home#privacypolicy'


  devise_for :users
  resources :reviews
  
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, path: 'our_two_cents'
  resources :services, path: 'whatwedo'
  resources :sections, except: [ :show]
  root 'home#index'

  # resources :services, path: 'whatwedo', :except => [:edit, :new, :destroy] do
  # 	resources :sections, path: ''
  #   # , only: [:index, :show]
  # end


  resources :works do
    resources :blocks
  end


  resources :services, path: 'whatwedo'  do
    resources :sections, path: 'topic'
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :work
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged

	has_attached_file :featuredimage, styles: { medium: "600x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :featuredimage, content_type: /\Aimage\/.*\z/

end

app/models/review.rb
class Review < ApplicationRecord

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

app/models/section.rb
class Section < ApplicationRecord

	belongs_to :service

	extend FriendlyId
	friendly_id :title, use: :slugged
	
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :sections
	
	extend FriendlyId
	friendly_id :title, use: :slugged

	
	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # , :registerable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord

	extend FriendlyId
	friendly_id :company_name, use: :slugged

	has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

	has_many :blocks

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  def index
    @blocks = Block.order("created_at DESC")
  end

  def show
  end

  def new
    @block = Block.new
  end

  def edit
  end

  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_block
      @block = Block.find(params[:id])
    end

    def block_params
      params.require(:block).permit(:work_id, :title, :block_style, :content, :block_type, :block_width, :block_content_wrapper)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

		@title = 'Web development Agency'
		@description = 'Msugroo Landing page'
		@keywords = 'Somali web development agency, Webdevelopment agency, london web development agency'

		@posts = Post.order("created_at DESC").limit(3)
		@works = Work.order("created_at DESC").limit(4)
	end

	def whoweare
	end

	def letstalk
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]


  def index
    @posts = Post.all
  end

  def show
    @posts = Post.where.not(id: @post.id).order("RANDOM()").limit(3)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :user_id, :featuredimage)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @works = Work.all
  end

  def show
    @page_title       = @work.company_name
    @page_keywords    = @work.company_name

    @blocks = Block.where(work_id: @work.id).order("created_at ASC")
  end

  def new
    @work = Work.new
  end

  def edit
  end

  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_work
      @work = Work.friendly.find(params[:id])
    end

    def work_params
      params.require(:work).permit(:company_name, :industry, :url, :website, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def random_review
		Review.order("RANDOM()").first
	end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/services_helper.rb
module ServicesHelper

	def services
		Service.order("created_at ASC")
	end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :featuredimage %>
    <%= form.file_field :featuredimage, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <!-- <trix-editor input="post_content"></trix-editor> -->

    <%= form.cktext_area :content, class: 'form-control'  %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit 'Publish', class: 'btn-large' %>
  </div>
<% end %>


<style>
  body {
    background: white !important; 
  }
</style>

app/views/posts/edit.html.erb
<div class="_page">

	<div class="container">

		<h1>Editing Post</h1>

		<%= render 'form', post: @post %>

		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/index.html.erb
<% set_meta_tags title: 'Our Two Cents',
                 description: 'Topics we are talking about',
                 keywords: 'Somali web development agency, Webdevelopment agency, london web development agency' %>


<div class="_page">
  <div class="small_space"></div>
  <div class="container">
    <p id="notice"><%= notice %></p>

    <div class="row">
     
      <div class="col">
        
        <div class="row">
          
          <% @posts.each do |post| %>
            <div class="col-md-6 post_item">
              <a href="<%= post_path(post)%>">
                <% if post.featuredimage? %>
                  <div class="cover_photo" style="background-image: url(<%= post.featuredimage(:medium)%>)"></div>
                <% end %>
                <% if post.featuredimage? %>
                    <div class="info">
                      <h1 class="title"><%= truncate(post.title, length: 60) %></h1>
                      <% else %>
                      <div class="info-full">
                        <h1 class="title"><%= truncate(post.title, length: 60) %></h1>
                  <% end %>
                  <p class="time"><%= time_ago_in_words(post.created_at) %></p>
                </div>
              </a>
            </div>
          <% end %>
          
        </div>

      </div>

      <div class="col-md-4">
        <div class="cta_box"></div>
      </div>

    </div>
    
    
      <%#= post.title %>
      <%#= post.content %>
      <%#= link_to 'Show', post %>
      <%#= link_to 'Edit', edit_post_path(post) %>
      <%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    

      <br>
      <% if user_signed_in? %>
        <%= link_to 'New Post', new_post_path %>
      <% end %>

    </div>

    <div class="spaced_footer"></div>
</div>

app/views/posts/new.html.erb
<div class="_page post">

	<section class="sectionfiller">
		<div class="container boxIt">

		  	<h1>New Post</h1>
			<%= render 'form', post: @post %>
		</div>
	</section>
</div>

app/views/posts/show.html.erb
<% set_meta_tags title: @post.title,
                 description: 'hello world',
                 keywords: 'Somali web development agency, Webdevelopment agency, london web development agency'
                 %>


<div class="_page post">

	<section class="sectionfiller">
	    <div class="container boxIt">
	        <div class="time_ago">
	        	<%= time_ago_in_words( @post.created_at)%> ago
	        </div>
	        <h1 class="title"><%= @post.title %></h1>
	        <div class="user_name">
	        	By <a href="#">MOHAMED HASSAN</a>
	        </div>
	        
	    </div>

	    <% if @post.featuredimage? %>
	    	<div class="featuredImage" style="background-image: url('<%= @post.featuredimage(:original) %>')">
	    	</div>
	    <% end %>

	</section>

	<section class="sectionfiller">
		<div class="container boxIt">
	        <div class="content">
	            <%= @post.content.html_safe %>
	        </div>
	    </div>
	</section>

	

	<div class="related_topics">
		<div class="container">

			<div>
				<h3 class="related_title">RELATED TOPICS</h3>
			</div>
			<div class="row">

			<% @posts.each do |post| %>
	            <div class="col post_item">
	              <a href="<%= post_path(post)%>">
	                <% if post.featuredimage? %>
	                  <div class="cover_photo" style="background-image: url(<%= post.featuredimage(:medium)%>)"></div>
	                <% end %>
	                <% if post.featuredimage? %>
	                    <div class="info">
	                      <h1 class="title"><%= truncate(post.title, length: 60) %></h1>
	                      <% else %>
	                      <div class="info-full">
	                        <h1 class="title"><%= truncate(post.title, length: 60) %></h1>
	                  <% end %>
	                  <p class="time"><%= time_ago_in_words(post.created_at) %> ago</p>
	                </div>
	              </a>
	            </div>
			<% end %>
			</div>
		</div>
	</div>


<!-- <div class="spaced_footer"></div> -->
</div>

app/views/works/_form.html.erb
<%= form_with(model: work, local: true) do |form| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: 'form-control' %>
  </div>

  <br>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control'  %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, class: 'form-control'  %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit 'Publish', class: 'btn-large'  %>
  </div>
<% end %>

app/views/works/edit.html.erb
<div class="_page">

<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

</div>

app/views/works/index.html.erb
<div class="_page">

  <section class="sectionfiller">
    <div class="container boxIt">
        <h1 class="title">OUR WORK</h1>
        <p class="content">
            We do Digital. We’re your web design company, web development agency and digital marketing team all rolled into one very special integrated digital service.
        </p>
    </div>

    <br><br>
  </section>

  <div class="container">

    <div class="workwrapper">


      <% @works.each do |work| %>
        <div class="work" style="background-image: url(<%= work.cover(:original)%>);">
          <a href="<%= work_path(work) %>">
            <div class="coverbg">
              <div class="info">
                <div class="company"><%= work.company_name %></div>
                <div class="industry"><%= work.industry %></div>
              </div>
            </div>
          </a>
        </div>
        <%#= link_to 'Show', work %>
        <%#= link_to 'Edit', edit_work_path(work) %>
        <%#= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>

      <% if user_signed_in? %>
        <div class="container">
          <%#= link_to 'New Work', new_work_path %>
      </div>
      <% end %>

  </div>

  </div>
</div>

app/views/works/new.html.erb
<div class="_page">

	<section class="sectionfiller">
		<div class="container boxIt">
			<h1>New Work</h1>
			<%= render 'form', work: @work %>
		</div>
	</section>

</div>

app/views/works/show.html.erb
<div class="work_featured_image_parallax" style="background-image: url(<%= @work.cover(:original)%>);">
</div>
<div class="works">
<section class="work_featured_image" >
  <!-- style="background-image: url(<%#= @work.cover(:original)%>);" -->

  <div class="fullcover">
    
    <div class="info">

      <div class="shati animated fadeInDown">
        <div class="company">
          <%= @work.company_name %>
        </div>
        <div class="industry">
          <%= @work.industry %>
        </div>
      </div>

      <div class="website">

        <% if @work.url? %>
          
          <a href="<%= @work.url %>">
            Visit <%= @work.website %>
          </a>
        <% end %>

      </div>

    </div>
  </div>
</section>

</div>

<div class="_page works">
<% @work.blocks.each do |block| %>
<% if block.block_content_wrapper == 'list' %>
  <div class="list">
    <section class="sectionfiller">
    <div class="content">
      <%= block.content.html_safe %>
    </div>
  </section>
  </div>

<% end %>


<% if block.block_content_wrapper == 'section' %>
  <section class="sectionfiller section_boxed">

    <%= block.title %> 
    <div class="content">
      <%= block.content.html_safe %> 
    </div>

  </section>
<% end %>

<% if block.block_content_wrapper == 'div' %>

  <div class="sectionfiller section_boxed">

    <%= block.title %> 
    <div class="content">
      <%= block.content.html_safe %> 
    </div>
    
  </div>

<% end %>

<!-- 
  <section class="sectionfiller">
    <% if block.block_width == 'boxed' %>
    <div class="section_boxed content <%= block.block_type %>">
      <% if block.block_type == 'text_only' %>
      <% if block.title? %>
        <h2 class="title">
          <%= block.title %> 
        </h2>
      <% end %>
        <div class="content">
          <%= block.content.html_safe %>
        </div>
      <% end %>
    </div>

    <% elsif block.block_width == 'fullwidth' %>
      <div class="section_full_width">
        <%= block.title %>

        <div class="content">
          <%= block.content.html_safe %>
        </div>
      </div>

      <% else %>
        <%= block.title %>
    <% end %>
  </section> -->
<% end %>




<% if user_signed_in? %>
	<div class="container">
		<%= link_to 'Edit', edit_work_path(@work) %> |
		<%= link_to 'Back', works_path %>
	</div>
<% end %>


</div>

<style>
  #nav {
    background: transparent;
  }

  #nav .NavLink {
    color:  #f1f1f1;
  }

  #nav .NavLink:hover {
    color:  white;
  }

  #nav .sitename {
    color:  #f1f1f1;
  }

  .symbol {
    background-image: url('/logo_white.svg') !important;
  }
</style>